# Generated by Django 5.1 on 2024-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('thumbnail', models.URLField(max_length=255)),
                ('bill_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
